hunter_config(OpenEXR VERSION "1.0.1" CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=YES)
hunter_config(ZLIB VERSION "1.2.8-p3" CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=YES)
hunter_config(PNG VERSION "1.6.16-p4" CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=YES)
