SET(LIBRARY_PATHS
    HINTS
    $ENV{EXR_DIR}
    ${CMAKE_INSTALL_PREFIX}
    PATH_SUFFIXES lib64 lib
    PATHS
    /usr/
    /usr/local/
    /opt/local/
)

FIND_PATH(OPENEXR_INCLUDE_DIR ImfHeader.h
    HINTS
    $ENV{EXR_DIR}
    ${CMAKE_INSTALL_PREFIX}
    PATH_SUFFIXES OpenEXR
    PATHS
    /usr/include       
    /usr/local/include  
    /opt/local/include
)

set(EXR_BIN_VER 2_2)

FIND_LIBRARY(OPENEXR_HALF_LIBRARY       NAMES Half                                  PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(OPENEXR_IEX_LIBRARY        NAMES Iex Iex-${EXR_BIN_VER}                PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(OPENEXR_IMATH_LIBRARY      NAMES Imath Imath-${EXR_BIN_VER}            PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(OPENEXR_ILMIMF_LIBRARY     NAMES IlmImf IlmImf-${EXR_BIN_VER}          PATHS ${LIBRARY_PATHS})
FIND_LIBRARY(OPENEXR_ILMTHREAD_LIBRARY  NAMES IlmThread IlmThread-${EXR_BIN_VER}    PATHS ${LIBRARY_PATHS})

SET(OPENEXR_INCLUDE_DIRS ${OPENEXR_INCLUDE_DIR})
SET(OPENEXR_LIBRARIES ${OPENEXR_HALF_LIBRARY} ${OPENEXR_IEX_LIBRARY} ${OPENEXR_IMATH_LIBRARY} ${OPENEXR_ILMIMF_LIBRARY} ${OPENEXR_ILMTHREAD_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENEXR DEFAULT_MSG OPENEXR_INCLUDE_DIR OPENEXR_HALF_LIBRARY OPENEXR_IEX_LIBRARY OPENEXR_IMATH_LIBRARY OPENEXR_ILMIMF_LIBRARY OPENEXR_ILMTHREAD_LIBRARY)
